#!/bin/bash
# GROMACS preparation pipeline commands
# Generated by gromacs_prepare.py
#
# This script reproduces all GROMACS commands executed by the Python script.
# You can run this independently to get the same results.
#

set -e  # Exit on error

