#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.8"
# dependencies = [
#     "shtab",
#     "numpy>=1.20",
#     "matplotlib>=3.5",
# ]
# ///
"""Generate bash Tab-completion files for gromacs_tools commands from their argparse options.

Usage:
  completions/generate.py           (re)write completions/<tool>.bash for every tool below
  completions/generate.py --check   only check: exit 1 if a completion file is out of date

Run it after changing a tool's command-line options, and commit the updated .bash file
together with that change. The .bash files are loaded by the shell (see README in this
folder), so completion itself never runs Python and is instant.
"""
import argparse
import sys
from pathlib import Path

import shtab

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "bin"))


def plot_xvg_parser():
    """plot_xvg.py's parser, with value suggestions for options argparse doesn't restrict."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import plot_xvg

    parser = plot_xvg.setup_argument_parser()
    parser.prog = "plot_xvg.py"  # the command name the completion is registered for

    try:  # Matplotlib >= 3.9
        from matplotlib.backends import backend_registry
        backends = backend_registry.list_builtin()
    except ImportError:
        from matplotlib import rcsetup
        backends = rcsetup.all_backends
    suggestions = {
        "--colormap": sorted(matplotlib.colormaps),
        "--plot-style": ["available"] + sorted(plt.style.available),
        "--backend": sorted(backends),
    }
    for action in parser._actions:
        if action.dest == "files" or "--output" in action.option_strings:
            action.complete = shtab.FILE
        for opt, values in suggestions.items():
            if opt in action.option_strings:
                action.choices = values  # only affects the completion file, not plot_xvg.py
    return parser


# Command name -> function returning its configured parser
TOOLS = {
    "plot_xvg": plot_xvg_parser,
}

HEADER = ("# bash Tab completion for {prog}\n"
          "# Generated by completions/generate.py from the tool's options: do not edit by hand,\n"
          "# run completions/generate.py instead after changing the options.\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="only check that the completion files are up to date")
    args = ap.parse_args()

    stale = []
    for name, make_parser in TOOLS.items():
        parser = make_parser()
        text = HEADER.format(prog=parser.prog) + shtab.complete(parser, shell="bash")
        out = HERE / f"{name}.bash"
        current = out.read_text() if out.exists() else None
        if args.check:
            if current != text:
                stale.append(out.name)
        elif current != text:
            out.write_text(text)
            print(f"Written: {out}")
        else:
            print(f"Up to date: {out}")

    if stale:
        print("Out of date (run completions/generate.py): " + ", ".join(stale), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
