# bash Tab completion for plot_xvg.py
# Generated by completions/generate.py from the tool's options: do not edit by hand,
# run completions/generate.py instead after changing the options.
# AUTOMATICALLY GENERATED by https://github.com/tqdm/shtab
# Usage:
# 1) Copy this to somewhere (e.g. ~/.local/share/bash_completion/plot_xvg.py).
# 2) Add the following line to your .bashrc:
#    source ~/.local/share/bash_completion/plot_xvg.py
# See also: https://github.com/scop/bash-completion/blob/main/doc/configuration.md



_shtab_plot_xvg_py_option_strings=(-h --help --moving-avg --ma --window -w --style -s --scatter --histogram --hist --xy-correlation --xycorr --2d --3d --bins --markersize --ms --colormap --cmap --multi -m --legends -l --output -o --title -t --no-subtitle --stats --xlabel --ylabel --figsize --aspect --xlim --ylim --plot-style --fontsize --fs --dpi --backend --mpl-backend --webagg-host --start --end --columns --cols --xcol)

_shtab_plot_xvg_py_pos_0_COMPGEN=_shtab_compgen_files
_shtab_plot_xvg_py___output_COMPGEN=_shtab_compgen_files
_shtab_plot_xvg_py__o_COMPGEN=_shtab_compgen_files

_shtab_plot_xvg_py___style_choices=(dots lines lines+dots)
_shtab_plot_xvg_py__s_choices=(dots lines lines+dots)
_shtab_plot_xvg_py___colormap_choices=(Accent Accent_r Blues Blues_r BrBG BrBG_r BuGn BuGn_r BuPu BuPu_r CMRmap CMRmap_r Dark2 Dark2_r GnBu GnBu_r Grays Grays_r Greens Greens_r Greys Greys_r OrRd OrRd_r Oranges Oranges_r PRGn PRGn_r Paired Paired_r Pastel1 Pastel1_r Pastel2 Pastel2_r PiYG PiYG_r PuBu PuBuGn PuBuGn_r PuBu_r PuOr PuOr_r PuRd PuRd_r Purples Purples_r RdBu RdBu_r RdGy RdGy_r RdPu RdPu_r RdYlBu RdYlBu_r RdYlGn RdYlGn_r Reds Reds_r Set1 Set1_r Set2 Set2_r Set3 Set3_r Spectral Spectral_r Wistia Wistia_r YlGn YlGnBu YlGnBu_r YlGn_r YlOrBr YlOrBr_r YlOrRd YlOrRd_r afmhot afmhot_r autumn autumn_r berlin berlin_r binary binary_r bone bone_r brg brg_r bwr bwr_r cividis cividis_r cool cool_r coolwarm coolwarm_r copper copper_r cubehelix cubehelix_r flag flag_r gist_earth gist_earth_r gist_gray gist_gray_r gist_grey gist_grey_r gist_heat gist_heat_r gist_ncar gist_ncar_r gist_rainbow gist_rainbow_r gist_stern gist_stern_r gist_yarg gist_yarg_r gist_yerg gist_yerg_r gnuplot gnuplot2 gnuplot2_r gnuplot_r gray gray_r grey grey_r hot hot_r hsv hsv_r inferno inferno_r jet jet_r magma magma_r managua managua_r nipy_spectral nipy_spectral_r ocean ocean_r okabe_ito okabe_ito_r pink pink_r plasma plasma_r prism prism_r rainbow rainbow_r seismic seismic_r spring spring_r summer summer_r tab10 tab10_r tab20 tab20_r tab20b tab20b_r tab20c tab20c_r terrain terrain_r turbo turbo_r twilight twilight_r twilight_shifted twilight_shifted_r vanimo vanimo_r viridis viridis_r winter winter_r)
_shtab_plot_xvg_py___cmap_choices=(Accent Accent_r Blues Blues_r BrBG BrBG_r BuGn BuGn_r BuPu BuPu_r CMRmap CMRmap_r Dark2 Dark2_r GnBu GnBu_r Grays Grays_r Greens Greens_r Greys Greys_r OrRd OrRd_r Oranges Oranges_r PRGn PRGn_r Paired Paired_r Pastel1 Pastel1_r Pastel2 Pastel2_r PiYG PiYG_r PuBu PuBuGn PuBuGn_r PuBu_r PuOr PuOr_r PuRd PuRd_r Purples Purples_r RdBu RdBu_r RdGy RdGy_r RdPu RdPu_r RdYlBu RdYlBu_r RdYlGn RdYlGn_r Reds Reds_r Set1 Set1_r Set2 Set2_r Set3 Set3_r Spectral Spectral_r Wistia Wistia_r YlGn YlGnBu YlGnBu_r YlGn_r YlOrBr YlOrBr_r YlOrRd YlOrRd_r afmhot afmhot_r autumn autumn_r berlin berlin_r binary binary_r bone bone_r brg brg_r bwr bwr_r cividis cividis_r cool cool_r coolwarm coolwarm_r copper copper_r cubehelix cubehelix_r flag flag_r gist_earth gist_earth_r gist_gray gist_gray_r gist_grey gist_grey_r gist_heat gist_heat_r gist_ncar gist_ncar_r gist_rainbow gist_rainbow_r gist_stern gist_stern_r gist_yarg gist_yarg_r gist_yerg gist_yerg_r gnuplot gnuplot2 gnuplot2_r gnuplot_r gray gray_r grey grey_r hot hot_r hsv hsv_r inferno inferno_r jet jet_r magma magma_r managua managua_r nipy_spectral nipy_spectral_r ocean ocean_r okabe_ito okabe_ito_r pink pink_r plasma plasma_r prism prism_r rainbow rainbow_r seismic seismic_r spring spring_r summer summer_r tab10 tab10_r tab20 tab20_r tab20b tab20b_r tab20c tab20c_r terrain terrain_r turbo turbo_r twilight twilight_r twilight_shifted twilight_shifted_r vanimo vanimo_r viridis viridis_r winter winter_r)
_shtab_plot_xvg_py___plot_style_choices=(available Solarize_Light2 bmh classic dark_background fast fivethirtyeight ggplot grayscale petroff10 petroff6 petroff8 seaborn-v0_8 seaborn-v0_8-bright seaborn-v0_8-colorblind seaborn-v0_8-dark seaborn-v0_8-dark-palette seaborn-v0_8-darkgrid seaborn-v0_8-deep seaborn-v0_8-muted seaborn-v0_8-notebook seaborn-v0_8-paper seaborn-v0_8-pastel seaborn-v0_8-poster seaborn-v0_8-talk seaborn-v0_8-ticks seaborn-v0_8-white seaborn-v0_8-whitegrid tableau-colorblind10)
_shtab_plot_xvg_py___backend_choices=(agg cairo gtk3agg gtk3cairo gtk4agg gtk4cairo macosx nbagg notebook pdf pgf ps qt5agg qt5cairo qtagg qtcairo svg template tkagg tkcairo webagg wx wxagg wxcairo)
_shtab_plot_xvg_py___mpl_backend_choices=(agg cairo gtk3agg gtk3cairo gtk4agg gtk4cairo macosx nbagg notebook pdf pgf ps qt5agg qt5cairo qtagg qtcairo svg template tkagg tkcairo webagg wx wxagg wxcairo)

_shtab_plot_xvg_py_pos_0_nargs=+
_shtab_plot_xvg_py__h_nargs=0
_shtab_plot_xvg_py___help_nargs=0
_shtab_plot_xvg_py___moving_avg_nargs=0
_shtab_plot_xvg_py___ma_nargs=0
_shtab_plot_xvg_py___scatter_nargs=0
_shtab_plot_xvg_py___histogram_nargs=0
_shtab_plot_xvg_py___hist_nargs=0
_shtab_plot_xvg_py___xy_correlation_nargs=0
_shtab_plot_xvg_py___xycorr_nargs=0
_shtab_plot_xvg_py___2d_nargs=0
_shtab_plot_xvg_py___3d_nargs=0
_shtab_plot_xvg_py___multi_nargs=0
_shtab_plot_xvg_py__m_nargs=0
_shtab_plot_xvg_py___legends_nargs=+
_shtab_plot_xvg_py__l_nargs=+
_shtab_plot_xvg_py___no_subtitle_nargs=0
_shtab_plot_xvg_py___stats_nargs=0
_shtab_plot_xvg_py___figsize_nargs=2
_shtab_plot_xvg_py___xlim_nargs=2
_shtab_plot_xvg_py___ylim_nargs=2
_shtab_plot_xvg_py___columns_nargs=+
_shtab_plot_xvg_py___cols_nargs=+


# $1=COMP_WORDS[1]
_shtab_compgen_files() {
  compgen -f -- $1  # files
}

# $1=COMP_WORDS[1]
_shtab_compgen_dirs() {
  compgen -d -- $1  # recurse into subdirs
}

# $1=COMP_WORDS[1]
_shtab_replace_nonword() {
  echo "${1//[^[:word:]]/_}"
}

# set default values (called for the initial parser & any subparsers)
_set_parser_defaults() {
  local subparsers_var="${prefix}_subparsers[@]"
  sub_parsers=${!subparsers_var-}

  local current_option_strings_var="${prefix}_option_strings[@]"
  current_option_strings=${!current_option_strings_var}

  completed_positional_actions=0

  _set_new_action "pos_$completed_positional_actions" true
}

# $1=action identifier
# $2=positional action (bool)
# set all identifiers for an action's parameters
_set_new_action() {
  current_action="${prefix}_$(_shtab_replace_nonword $1)"

  local current_action_compgen_var=${current_action}_COMPGEN
  current_action_compgen="${!current_action_compgen_var-}"

  local current_action_choices_var="${current_action}_choices[@]"
  current_action_choices="${!current_action_choices_var-}"

  local current_action_nargs_var="${current_action}_nargs"
  if [ -n "${!current_action_nargs_var-}" ]; then
    current_action_nargs="${!current_action_nargs_var}"
  else
    current_action_nargs=1
  fi

  current_action_args_start_index=$(( $word_index + 1 - $pos_only ))

  current_action_is_positional=$2
}

# Notes:
# `COMPREPLY`: what will be rendered after completion is triggered
# `completing_word`: currently typed word to generate completions for
# `${!var}`: evaluates the content of `var` and expand its content as a variable
#     hello="world"
#     x="hello"
#     ${!x} -> ${hello} -> "world"
_shtab_plot_xvg_py() {
  local completing_word="${COMP_WORDS[COMP_CWORD]}"
  local previous_word="${COMP_WORDS[COMP_CWORD-1]}"
  local completed_positional_actions
  local current_action
  local current_action_args_start_index
  local current_action_choices
  local current_action_compgen
  local current_action_is_positional
  local current_action_nargs
  local current_option_strings
  local sub_parsers
  COMPREPLY=()

  local prefix=_shtab_plot_xvg_py
  local word_index=0
  local pos_only=0 # "--" delimiter not encountered yet
  _set_parser_defaults
  word_index=1

  # determine what arguments are appropriate for the current state
  # of the arg parser
  while [ $word_index -ne $COMP_CWORD ]; do
    local this_word="${COMP_WORDS[$word_index]}"

    if [[ $pos_only = 1 || " $this_word " != " -- " ]]; then
      if [[ -n $sub_parsers && " ${sub_parsers[@]} " == *" $this_word "* ]]; then
        # valid subcommand: add it to the prefix & reset the current action
        prefix="${prefix}_$(_shtab_replace_nonword $this_word)"
        _set_parser_defaults
      fi

      if [[ " ${current_option_strings[@]} " == *" $this_word "* ]]; then
        # a new action should be acquired (due to recognised option string or
        # no more input expected from current action);
        # the next positional action can fill in here
        _set_new_action $this_word false
      fi

      if [[ "$current_action_nargs" != "*" ]] && \
         [[ "$current_action_nargs" != "+" ]] && \
         [[ "$current_action_nargs" != "?" ]] && \
         [[ "$current_action_nargs" != *"..." ]] && \
         (( $word_index + 1 - $current_action_args_start_index - $pos_only >= \
            $current_action_nargs )); then
        $current_action_is_positional && let "completed_positional_actions += 1"
        _set_new_action "pos_$completed_positional_actions" true
      fi
    else
      pos_only=1 # "--" delimiter encountered
    fi

    let "word_index+=1"
  done

  # Generate the completions

  COMPREPLY=()
  if [[ $pos_only = 0 && "$completing_word" == -* &&
        ( -z "$current_action_compgen" || "$current_action_is_positional" = true ) ]]; then
    # optional argument started: use option strings
    while IFS= read -r line; do COMPREPLY+=("$line"); done < <(
      compgen -W "${current_option_strings[*]}" -- "$completing_word")
  elif [[ "$previous_word" =~ ^[0-9\&]*[\<\>]\>?$ ]]; then
    # handle redirection operators
    compopt -o filenames 2>/dev/null || : # bash>=4
    while IFS= read -r line; do COMPREPLY+=("$line"); done < <(compgen -f -- "$completing_word")
  else
    # use choices & compgen
    local action_compgen_word="$completing_word"
    # handle tab-completing in the middle of a line (#248 <- #116)
    [[ -n "$current_action_compgen" && "$completing_word" == -* ]] && action_compgen_word=""
    [ -n "$current_action_compgen" ] && {
      [[ "$current_action_compgen" =~ _(file|dir|glob|FILE|DIR|GLOB)|File|Dir|Glob ]] &&
        compopt -o filenames 2>/dev/null || : # bash>=4
      while IFS= read -r line; do COMPREPLY+=("$line"); done < <(
        "$current_action_compgen" "$action_compgen_word")
    }
    while IFS= read -r line; do COMPREPLY+=("$line"); done < <(
      compgen -W "${current_action_choices[*]}" -- "$completing_word")
  fi

  return 0
}

complete -F _shtab_plot_xvg_py plot_xvg.py